server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://PostgreSQL:5432/cottage_connect
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  web:
    locale: en
    resources:
      static-locations: file:src/main/resources/static/, classpath:/static/
      cache:
        period: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
application:
  security:
    jwt:
      secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      expiration: 1800000
      refresh-token:
        expiration: 1800000
