CREATE TABLE _VILLAGE_POST
(
    VILLAGE_POST_ID SERIAL                   NOT NULL,
    TITLE           VARCHAR(255)             NOT NULL,
    CONTENT         VARCHAR(255)             NOT NULL,
    CREATED_AT      TIMESTAMP WITH TIME ZONE NOT NULL,
    VILLAGE_ID      BIGINT                   NOT NULL,
    USER_ID         BIGINT                   NOT NULL,
    PRIMARY KEY (VILLAGE_POST_ID),
    CONSTRAINT FK_VILLAGE_POST_VILLAGE_ID
        FOREIGN KEY (VILLAGE_ID)
            REFERENCES _VILLAGE (VILLAGE_ID),
    CONSTRAINT FK_VILLAGE_POST_USER
        FOREIGN KEY (USER_ID)
            REFERENCES _USER (USER_ID)
);