CREATE TABLE _COMMENT
(
    COMMENT_ID       SERIAL       NOT NULL,
    CONTENT          VARCHAR(255) NOT NULL,
    COMMENTABLE_TYPE VARCHAR(50)  NOT NULL,
    COMMENTABLE_ID   BIGINT       NOT NULL,
    RATING           INTEGER      NOT NULL,
    USER_ID          INTEGER      NOT NULL,
    PRIMARY KEY (COMMENT_ID),
    CONSTRAINT FK_COMMENT_USER
        FOREIGN KEY (USER_ID)
            REFERENCES _USER (USER_ID)
);