CREATE TABLE _VILLAGE
(
    VILLAGE_ID  SERIAL       NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    ADDRESS_ID  BIGINT       NOT NULL,
    OWNER_ID    BIGINT       NOT NULL,
    PRIMARY KEY (VILLAGE_ID),
    CONSTRAINT FK_VILLAGE_ADDRESS
        FOREIGN KEY (ADDRESS_ID)
            REFERENCES _ADDRESS (ADDRESS_ID),
    CONSTRAINT FK_VILLAGE_OWNER
        FOREIGN KEY (OWNER_ID)
            REFERENCES _OWNER (OWNER_ID)
);