CREATE TABLE _PHOTO
(
    PHOTO_ID       SERIAL       NOT NULL,
    PHOTOABLE_TYPE VARCHAR(50)  NOT NULL,
    PHOTOABLE_ID   BIGINT       NOT NULL,
    PATH           VARCHAR(256) NOT NULL,
    PRIMARY KEY (PHOTO_ID)
);