CREATE TABLE _COTTAGE
(
    COTTAGE_ID     SERIAL        NOT NULL,
    COTTAGE_NUMBER INTEGER       NOT NULL,
    COTTAGE_SIZE   INTEGER       NOT NULL,
    PRICE          NUMERIC(7, 2) NOT NULL,
    DESCRIPTION    VARCHAR(255)  NOT NULL,
    VILLAGE_ID     BIGINT        NOT NULL,
    PRIMARY KEY (COTTAGE_ID),
    CONSTRAINT FK_COTTAGE_VILLAGE
        FOREIGN KEY (VILLAGE_ID)
            REFERENCES _VILLAGE (VILLAGE_ID)
);