CREATE TABLE _LIKE
(
    LIKE_ID       SERIAL      NOT NULL,
    LIKEABLE_TYPE VARCHAR(50) NOT NULL,
    LIKEABLE_ID   BIGINT      NOT NULL,
    USER_ID       INTEGER     NOT NULL,
    PRIMARY KEY (LIKE_ID),
    CONSTRAINT FK_LIKE_USER
        FOREIGN KEY (USER_ID)
            REFERENCES _USER (USER_ID)
);