CREATE TABLE _OWNER
(
    OWNER_ID  SERIAL      NOT NULL,
    FIRSTNAME VARCHAR(64) NOT NULL,
    LASTNAME  VARCHAR(64) NOT NULL,
    PHONE     VARCHAR(32) NOT NULL,
    USER_ID   BIGINT      NOT NULL,
    PRIMARY KEY (OWNER_ID),
    CONSTRAINT FK_OWNER_USER
        FOREIGN KEY (USER_ID)
            REFERENCES _USER (USER_ID)
);